version: '3.8'

services:
  db:
    build:
      context: ./mysql-dockerised
    container_name: mysql-multitenant
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: example1
    ports:
      - '3307:3306'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  web:
    build:
      context: .
    container_name: django-multitenant
    command: gunicorn multitenant_project.wsgi:application -c gunicorn.conf.py
    ports:
      - '8000:8000'
    depends_on:
      - db
    networks:
      - backend
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: rootpass

volumes:
  db_data:

networks:
  backend:
